pipeline {
  agent any

  parameters {
    booleanParam defaultValue: false, name: 'TFapply'
    booleanParam defaultValue: false, name: 'TFdestroy'
  }

  environment {
    AWS_ACCESS_KEY_ID     = credentials('jenkins-aws-access-key-id')
    AWS_SECRET_ACCESS_KEY = credentials('jenkins-aws-secret-access-key')

    WORKDIR = "./backend"
  }

  stages {
    stage('terraform init') {
      steps{
        dir(WORKDIR) {
          sh 'terraform init'
        }                            
      }
    }

    stage('terraform plan') {
      steps{
        dir(WORKDIR) {
          sh 'terraform plan'
        }                            
      }
    }

    stage('terraform apply') {
      steps{                
        dir(WORKDIR){
          when {expression{return params.TFapply}}
          sh 'terraform apply -auto-approve'
        }   
      }
    }
        
    stage('terraform destroy') {
      steps{
        when {expression{return params.TFdestroy}}
        dir(WORKDIR) {
          sh 'terraform destroy -auto-approve'}
      }
    }
  }
}